FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./api ./api
CMD ["uvicorn", "api.main:router", "--host", "0.0.0.0", "--port", "8000", "--reload"]