apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: Never
          command: ["celery", "-A", "worker.main", "worker", "--loglevel=info"]
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@postgres:5432/taskdb
            - name: REDIS_URL
              value: redis://redis:6379/0
