name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python 3.11
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort pytest

      - name: Run code formatter (Black)
        run: black --check .

      - name: Run import sorter (isort)
        run: isort . --check-only

      - name: Load environment variables
        run: |
          echo "TEST_DATABASE_URL=postgresql://admin_user:admin_pass@localhost:5432/test_task_manager_api_db" >> $GITHUB_ENV

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t fastapi-app -f Dockerfile.api .